return {
    "AstroNvim/astrocommunity",
    -- { import = "astrocommunity.pack.bash" },
    -- { import = "astrocommunity.pack.docker" },
    -- { import = "astrocommunity.pack.cue" },
    { import = "astrocommunity.pack.go" },
    -- { import = "astrocommunity.pack.helm" },
    -- { import = "astrocommunity.pack.html-css" },
    -- { import = "astrocommunity.pack.json" },
    -- { import = "astrocommunity.pack.lua" },
    -- { import = "astrocommunity.pack.markdown" },
    -- { import = "astrocommunity.pack.nix" },
    { import = "astrocommunity.pack.python" },
    -- { import = "astrocommunity.pack.ruby" },
    { import = "astrocommunity.pack.rust" },
    { import = "astrocommunity.pack.java" },
    -- { import = "astrocommunity.pack.svelte" },
    -- { import = "astrocommunity.pack.tailwindcss" },
    -- { import = "astrocommunity.pack.terraform" },
    -- { import = "astrocommunity.pack.toml" },
    -- { import = "astrocommunity.pack.typescript-all-in-one" },
    -- { import = "astrocommunity.pack.vue" },
    -- { import = "astrocommunity.pack.yaml" },
    { import = "astrocommunity.editing-support.vim-move" },
    { import = "astrocommunity.utility.noice-nvim" },
    { import = "astrocommunity.colorscheme.nightfox-nvim", enabled = true },
    { import = "astrocommunity.colorscheme.kanagawa-nvim", enabled = true },
    { import = "astrocommunity.colorscheme.rose-pine" },
    { import = "astrocommunity.colorscheme.catppuccin" },
  }